version: "3.7"
services:
  airflow-backend:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks: 
      - airflow-backend
    volumes:
      - "airflow-backend:/var/lib/mysql"
    env_file:
      - mysql.env
    
  airflow-engine:
    build: ./airflow-engine
    depends_on: 
      - airflow-backend
    networks: 
      - airflow-backend
    volumes:
      - "airflow-engine:/root/airflow/"
    ports:
      - "8080:8080"
    env_file:
      - mysql.env

networks:
  airflow-backend:

volumes:
  airflow-engine:
  airflow-backend:
